Link- https://rextester.com/MDVQ80847


SELECT SERVERPROPERTY('MachineName') As MachineName
SELECT SERVERPROPERTY('Edition') As Edition
SELECT SERVERPROPERTY('INSTANCEDEFAULTDATAPATH') As DataPath
SELECT SERVERPROPERTY('PRODUCTVERSION') As ProductVersion
SELECT SERVERPROPERTY('BUILDCLRVERSION') As CLR_Version
SELECT SERVERPROPERTY('PROCESSID') As Process_ID
SELECT SERVERPROPERTY('RESOURCELASTUPDATEDATETIME') As LastUpdate
SELECT SERVERPROPERTY('EditionID') As EditionID
SELECT SERVERPROPERTY('Collation') As Collation