Link- https://rextester.com/RKSK63042

CREATE SEQUENCE Sequence1
 AS INT
 START WITH 1
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 3
CYCLE

SELECT NEXT VALUE for Sequence1
SELECT NEXT VALUE for Sequence1
SELECT NEXT VALUE for Sequence1
SELECT NEXT VALUE for Sequence1
SELECT NEXT VALUE for Sequence1

CREATE SEQUENCE Sequence2
 AS INT
 START WITH 1
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 3
 
SELECT NEXT VALUE for Sequence2
SELECT NEXT VALUE for Sequence2
SELECT NEXT VALUE for Sequence2
SELECT NEXT VALUE for Sequence2
SELECT NEXT VALUE for Sequence2




 
 


